### ISSUE TITLE
About Dataset of Test

### ISSUE THREAD

**Issue by cainiaoshidai** [ZENGYIMING-EAMON/CorrNet3D#1]
Hi,

I download the file of `testset.h5`, and I found it include 
`['src_flat', 'tgt_flat', 'label_flat', 'scores_flat', 'sl_002', 'sl_004', 'sl_006', 'sl_008', 'sl_01', 'sl_012', 'sl_014', 'sl_016', 'sl_018', 'sl_02']`. 
I want to know what it all stands for.
 Thanks.

**Comment by ZENGYIMING-EAMON** [comment]
Hi, 'sl_xxx' means the soft label for specific error percentage, and the label_flat is the accurate GT label.
'src' and 'tat' means two input point clouds. And scores_flat is not used. If your just want to get the inputs and GT, use 'src_flat', 'tgt_flat', 'label_flat'.

**Comment by cainiaoshidai** [comment]
Hi, thanks for your reply. I would like to ask you another question. Is the test set you provided the FAUST data set?

Thanks.

**Comment by ZENGYIMING-EAMON** [comment]
It is the same as the train/test set used in the cited paper 3D-coded.

**Comment by cainiaoshidai** [comment]
Thanks, I think I know which dataset it is.
