### ISSUE TITLE
  from omegaconf.errors import UnsupportedValueType, ValidationError ImportError: cannot import name 'UnsupportedValueType' from 'omegaconf.errors' (/home/zzu/anaconda3/envs/corrnet3d/lib/python3.8/site-packages/omegaconf/errors.py)

### ISSUE THREAD

**Issue by ly16637857359** [ZENGYIMING-EAMON/CorrNet3D#12]
why when i run " python lit_corrnet3d_clean.py --gpus=3 --batch_size=20 --data_dir=/home/zzu/ly/code/CorrNet3D-main/date/trainset.h5 --test_data_dir=/home/zzu/ly/code/CorrNet3D-main/date/testset.h5‘’
error： from omegaconf.errors import UnsupportedValueType, ValidationError
ImportError: cannot import name 'UnsupportedValueType' from 'omegaconf.errors' (/home/zzu/anaconda3/envs/corrnet3d/lib/python3.8/site-packages/omegaconf/errors.py)

![1678689221441](https://user-images.githubusercontent.com/100392373/224624979-d9e80be6-4283-4f1a-bbec-a95b03cebc35.png)

**Comment by ly16637857359** [comment]
I've solved it

**Comment by sakshamjindal** [comment]
Can you tell how?

**Comment by ly16637857359** [comment]
不知道



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 05/08/2023 12:14 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [ZENGYIMING-EAMON/CorrNet3D] from omegaconf.errors import UnsupportedValueType, ValidationError ImportError: cannot import name 'UnsupportedValueType' from 'omegaconf.errors' (/home/zzu/anaconda3/envs/corrnet3d/lib/python3.8/site-packages/omegaconf/errors.py) (Issue #12) |

Can you tell how?

**Comment by AstorYH** [comment]
how you solve that error
