### ISSUE TITLE
How to see the result

### ISSUE THREAD

**Issue by caijinana** [ZENGYIMING-EAMON/CorrNet3D#4]
how to see the result visiable,and  i don't understand the meaning of the result now

**Comment by ZENGYIMING-EAMON** [comment]
Given the output flexible P_out matrix, first turn it into the hard 0-1 matrix using row max. Then you can get the corresponding pairs of points from the indices of the matrix. You may visually assign the same color for the corresponding points. And see the pattern of the color or draw the corresponding lines between the corresponding points.
