### ISSUE TITLE
关于使用自己的数据

### ISSUE THREAD

**Issue by cathylacus** [ZENGYIMING-EAMON/CorrNet3D#5]
感谢您的工作，我想请问一下，如何使用自己的数据来生成h5文件，谢谢

**Comment by ZENGYIMING-EAMON** [comment]
Hi, the dataset was made following this cited work:
https://github.com/ThibaultGROUEIX/3D-CODED
Basically, you just need to organize your data as multiple pairs of shapes for training and testing.
