### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by AtsushiHashimoto** [ZENGYIMING-EAMON/CorrNet3D#8]
Thank you for sharing your great work!

By the way, what is the license for this model? I'd like to use the model in our repository but cannot do it legally due to the lack of license information. It would help me (and probably many other people) greatly If you could provide a LICENSE file.

**Comment by ZENGYIMING-EAMON** [comment]
Thank you for your interest! I've added a license.

**Comment by AtsushiHashimoto** [comment]
Thank you for your swift response!
